# 自动推送到vue2分支
name: Trigger on Push
on:
  push:
    branches:
      - vue2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build or task steps here
